eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT:8080}

---

spring:
  profiles: swarm

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOST_NAME:localhost}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port: ${server.port:80}

  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/"

#server:
#  forward-headers-strategy: native

---

spring:
  profiles: dev
  cloud:
    inetutils:
      preferred-networks:
        - 10.0.7
#  boot:
#    admin:
#      ui:
#        public-url: https://web.dev.bremersee.org/admin

---

spring:
  profiles: prod
  cloud:
    inetutils:
      preferred-networks:
        - 172.16.1
#  boot:
#    admin:
#      ui:
#        public-url: https://admin.bremersee.org

