spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  boot:
    admin:
      notify:
        mail:
          enabled: false
eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
  endpoint:
    health:
      show-details: when_authorized
  health:
    mail:
      enabled: false

server:
  port: ${SERVER_PORT:8080}

bremersee:
  auth:
    role-definitions:
      admin:
        - "ROLE_ADMIN"

---

spring:
  profiles: in-memory

bremersee:
  auth:
    in-memory-users:
      - name: "admin"
        password: "admin"
        authorities:
          - "ROLE_USER"
          - "ROLE_ADMIN"
      - name: "actuator"
        password: "actuator"
        authorities:
          - "ROLE_ACTUATOR"
          - "ROLE_ACTUATOR_ADMIN"
      - name: "user"
        password: "user"
        authorities:
          - "ROLE_USER"
